[package]
name = "vec2dim"
version = "0.1.0"
authors = ["Colin Logue <email@colinlogue.me>"]
edition = "2018"
license = "MIT"
description = "Two-dimensional array"
readme = "README.md"
repository = "https://github.com/colinlogue/vec2dim/"

[dependencies]
